### ISSUE TITLE
[future request] Add tags and releases

### ISSUE THREAD

**Issue by sirlucjan** [goldstar611/gitless#22]
Would it be possible to add tags and releases? It would make it very easy for me to manage my package in AUR. So far I have to rely on commits.

**Comment by goldstar611** [comment]
Yes I can definitely do that. I need to decide how to name the tags so that there is some sense to them. Versioning is not something I've thought about just yet.

**Comment by sirlucjan** [comment]
I would actually have two suggestions.
First possibility - to keep the current numbering and release the next version e.g. as 0.8.9 or 0.9.0
Second possibility - release date as version number - for example v20220301
Both have their advantages. 

No matter what you choose - adding releases will certainly make packagers' jobs a lot easier.

**Comment by goldstar611** [comment]
I've added tags to the repository starting at 0.9.0. I'm going to leave this issue open so I can get a system in place to keep the version up to date. It's currently still at https://github.com/goldstar611/gitless/blob/07661cc724a6e3882051bd15c704d37df68e4896/gitless/cli/gl.py#L30 and I want to move that definition to a different place as well.

I'm open to the release date as well. Another project I like uses that scheme.

**Comment by sirlucjan** [comment]
Awesome, thanks a lot. 

Now my package in AUR looks as it should. 

https://aur.archlinux.org/packages/gitless

**Comment by sirlucjan** [comment]
Thanks a lot!
