### ISSUE TITLE
[future request] Adding the equivalent of git fetch

### ISSUE THREAD

**Issue by sirlucjan** [goldstar611/gitless#28]
One of the last features I'm missing in gitless (or maybe there is and I haven't managed to get to it) is the equivalent of git fetch. This would be very useful for synchronizing the fork with the upstream. Would it be possible to add this? I would be happy to test if necessary.

**Comment by goldstar611** [comment]
I agree, I find my self running `git fetch` as well as `git pull`. 

If I had to guess, a new git user wouldn't care/know and then see the error after running `gl publish` that a merge/fuse is necessary. This may not be your use case however.

I'd like to document the use case here. Are you using `git fetch` to keep track of new tags that are created or changes in a branch?

With that said, checkout the new `issue_28` branch :) https://github.com/goldstar611/gitless/tree/issue_28

[Edit] This wrapper could be developed to a pygit2 fetch call if it makes sense for the stated project goals. https://www.pygit2.org/remotes.html#pygit2.Remote.fetch

**Comment by sirlucjan** [comment]
I use git fetch to sync both branches and tags. I would like my fork to always be compatible with the upstream if necessary.

**Comment by sirlucjan** [comment]
A little later, I'll be happy to test it out. And what do you think about adding gl pull in addition to gl fetch? I use mirrors of my repositories very often and in fact I use git pull as much as git fetch and git push. Gitless is such a powerful project that I would like to use it as much as possible.

**Comment by sirlucjan** [comment]
It looks like everything is working. 

```lucjan at archlinux ~/GIT/github/gitless 12:59:55 6ec06313 master    
❯ gl fetch                
lucjan at archlinux ~/GIT/github/gitless 13:00:10 6ec06313 master    
❯ gl merge upstream/master
Found existing alias for "gl merge". You should use: "glm"
✔ Merge succeeded
lucjan at archlinux ~/GIT/github/gitless 13:00:18 74bd4044 master    
❯ gl publish              
Found existing alias for "gl publish". You should use: "glp"
Enter passphrase for key '/home/lucjan/.ssh/git': 
✔ Publish of commits from branch master to branch origin/master succeeded```

**Comment by sirlucjan** [comment]
I tried making a simple wrapper for gl pull and it seems to work.

https://github.com/goldstar611/gitless/pull/29/commits/a6efedfac954e4968b20341751bcb1d1dc87430c

**Comment by goldstar611** [comment]
Closed in https://github.com/goldstar611/gitless/commit/60b46b9f59b02d176f40a38e3cd5cda1b312f00f
